version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - "discovery.type=multi-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origi n=*"
    ports:
      - "9200:9200"
      - "9300:9300"
