version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origi n=*"
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
      - "9300:9300"

    deploy:
      resources:
        limits:
          memory: 16G